global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'mycmdb-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scheme: https
    tls_config:
      key_file: /data/prometheus.key
      cert_file: /data/prometheus.crt
      insecure_skip_verify: true
    static_configs:
      - targets: ['mycmdb:8443']
