CREATE TABLE CONFIGURATION_ITEMS (
  ID VARCHAR(250) PRIMARY KEY,
  CI_NAME VARCHAR(250) NOT NULL UNIQUE,
  AVAILABILITY_R SMALLINT NOT NULL,
  INTEGRITY_R SMALLINT NOT NULL,
  CONFIDENTIALITY_R SMALLINT NOT NULL,
  SYSTEM_OWNER VARCHAR(250) NOT NULL,
  TEAM_EMAIL VARCHAR(250) NOT NULL
);

CREATE INDEX CONFIGURATION_ITEMS_AIC_IDX ON CONFIGURATION_ITEMS (AVAILABILITY_R, INTEGRITY_R, CONFIDENTIALITY_R);
