CREATE TYPE COMPLIANCE_LEVEL AS ENUM ('BLOCKING', 'NON_BLOCKING');

CREATE TYPE STATUS AS ENUM ('CREATED', 'SUBMITTED', 'CANCELLED', 'COMPLETED');

CREATE TABLE COMPLIANCE_SHOTS (
  ID VARCHAR(250) PRIMARY KEY,
  TITLE VARCHAR(250) NOT NULL UNIQUE,
  SHORT_DESC VARCHAR(500) NOT NULL,
  REF_URL VARCHAR(250) NOT NULL,
  TUTORIAL_URL VARCHAR(500) NOT NULL,
  COMPLIANCE_LEVEL COMPLIANCE_LEVEL NOT NULL,
  MIN_AVAILABILITY_R SMALLINT NOT NULL,
  MIN_INTEGRITY_R SMALLINT NOT NULL,
  MIN_CONFIDENTIALITY_R SMALLINT NOT NULL,
  CREATED_BY VARCHAR(250) NOT NULL
);

CREATE TABLE CONFIGURATION_ITEMS (
    ID VARCHAR(250) PRIMARY KEY,
    EXTERNAL_ID VARCHAR(250),
    CI_NAME VARCHAR(250) NOT NULL,
    SYSTEM_OWNER VARCHAR(250) NOT NULL,
    TEAM_EMAIL VARCHAR(250) NOT NULL,
    EXTERNAL_CMDB_NAME VARCHAR(250) NOT NULL
);

CREATE TABLE COMPLIANCE_SHOTS_CONFIGURATION_ITEMS (
    STATUS STATUS,
    CONFIGURATION_ITEM_ID VARCHAR(255) NOT NULL,
    COMPLIANCE_SHOT_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (COMPLIANCE_SHOT_ID, CONFIGURATION_ITEM_ID)
);

ALTER TABLE COMPLIANCE_SHOTS
    ADD CONSTRAINT UK_fnqaouoxymisr1i147lyflpxa UNIQUE (TITLE);

ALTER TABLE CONFIGURATION_ITEMS
    ADD CONSTRAINT UK_7lvpw84emlc2hxvjtwdflp28h UNIQUE (CI_NAME);

ALTER TABLE COMPLIANCE_SHOTS_CONFIGURATION_ITEMS
    ADD CONSTRAINT FKj03abkbobt0surblx2s3trrty
        FOREIGN KEY (COMPLIANCE_SHOT_ID)
            REFERENCES COMPLIANCE_SHOTS;

ALTER TABLE COMPLIANCE_SHOTS_CONFIGURATION_ITEMS
    ADD CONSTRAINT FK3eqp6r20ajyblv7hw09m6n24f
        FOREIGN KEY (CONFIGURATION_ITEM_ID)
            REFERENCES CONFIGURATION_ITEMS(ID);


CREATE TABLE USERS (
    ID SERIAL  PRIMARY KEY,
    USERNAME VARCHAR(250) NOT NULL UNIQUE ,
    PASSWORD VARCHAR(250) NOT NULL,
    ROLE VARCHAR(250) DEFAULT NULL
);

ALTER TABLE USERS
    ADD CONSTRAINT UK_7lvpf89emlc2hxvjtksilp28h UNIQUE (USERNAME);

ALTER TABLE COMPLIANCE_SHOTS
    ADD CONSTRAINT FK3eqp6r13pjyblv3jw09m6c89f
        FOREIGN KEY (CREATED_BY)
            REFERENCES USERS(USERNAME);
